services:
  - type: web
    name: chhohreivung
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn chhohreivung.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chhohreivung.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: chhohreivung-db
          property: connectionString
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SITE_URL
        sync: false
      - key: USE_CLOUDINARY
        value: "True"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CONTACT_EMAIL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: "True"

databases:
  - name: chhohreivung-db
    plan: free
    databaseName: chhohreivung
    region: singapore
