# Generated by Django 4.2.30 on 2026-06-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
