# Generated by Django 5.2.15 on 2026-06-11 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_income_pageview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='blog_articl_status_8b18ca_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'featured', 'published_at'], name='blog_articl_status_3d3e42_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status', 'published_at'], name='blog_articl_categor_8afef1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-views'], name='blog_articl_views_a54989_idx'),
        ),
    ]
