# Generated by Django 5.2.15 on 2026-06-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_blog_articl_status_8b18ca_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.URLField(blank=True, default='', verbose_name='Featured Image URL'),
        ),
    ]
